- name: Installing Nginx
  hosts: all
  become: true
  tasks:
    - name: Install Nginx
      ansible.builtin.yum:
       name: nginx
       state: latest

    - name: Starting  Nginx
      ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

- name: Installing Nginx
  hosts: all
  become: true
  roles:
    - sample



