- name: Variable
  hosts: all
  vars:
    URL: google.com
  tasks:
    - name: Printing a variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Printing task level  variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
        vars:
          URL: task.google.com
