- name: Variable
  hosts: localhost
  connection: local
  vars:
    URL: play.google.com
  tasks:
    - name: Printing a variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}

    - name: Printing task level  variable
      ansible.builtin.debug:
        msg: URL = {{ URL }}
        vars:
          URL: task.google.com
