- name: Print Variable Type
  host: localhost
  connection: local
  vars:
    fruit: Apple
    for_sale: true
    quantity: 100
  tasks:
    - name: Print
      ansible.builtin.debug:
        msg: Fruit Name - {{ fruit }}, Quantity - {{ quantity }}
      when: for_sale
