- name: Loops in Ansible
  hosts: localhost
  connection: local
  vars:
    fruits:
      - Apple
      - Mango
      - Orange
  tasks:
    - name: Printing fruits
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop: "{{ fruits }}"

    - name: Printing Local
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item }}"
      loop:
        - Bananna
        - kiwi


    - name: Printing Local
      ansible.builtin.debug:
        msg: Fruit Name - "{{ item.name }}", Quantity - "{{ item.quantity }}"
      loop:
        - {name: Bananna,quantity: 100}
        - {name: Kiwi,quantity: 200}